In [1]:
import math

softmat_output=[0.9, 0.2, 0.1]
target_output=[1, 0, 0]

loss =-(math.log(softmat_output[0])*target_output[0]+
        math.log(softmat_output[0])*target_output[0]+
        math.log(softmat_output[0])*target_output[0])

print(loss)

0.31608154697347884


 A collection of softmax outputs and their intended targets, we can map these indices to
retrieve the values from the softmax distributions:

In [12]:
import math

softmax_output=[[0.7, 0.1, 0.2],
                [0.1, 0.5, 0.4],
                [0.02, 0.9, 0.08]]

class_targets=[0, 1, 1]

for  i, j in  zip(softmax_output, class_targets):
    print(i[j])



0.7
0.5
0.9


In [17]:
softmax_output=[[0.7, 0.1, 0.2],
                [0.1, 0.5, 0.4],
                [0.02, 0.9, 0.08]]

class_targets=[0, 1, 1]

result = [softmax_output[i][j] for i, j in enumerate(class_targets)]
print(result)

[0.7, 0.5, 0.9]


In [21]:
import numpy as np
softmax_output=[[0.7, 0.1, 0.2],
                [0.1, 0.5, 0.4],
                [0.02, 0.9, 0.08]]



class_targets=[0, 1, 1]

result = -np.log(np.array([softmax_output[i][j] for i, j in enumerate(class_targets)]))
print(result)

print(np.mean(result))

[0.35667494 0.69314718 0.10536052]
0.38506088005216804


In [3]:
import numpy as np
softmax_output=np.array([[0.7, 0.1, 0.2],
                [0.1, 0.5, 0.4],
                [0.02, 0.9, 0.08]])

class_targets=np.array([[0, 1, 1],
                       [0, 1, 1],
                       [0, 1, 0]])

if len(class_targets.shape)==1:
  correct_confidences = [softmax_output[i][j] for i, j in enumerate(class_targets)]
  print(correct_confidences)

elif len(class_targets.shape)==2:
  correct_confidences = np.sum(softmax_output*class_targets, axis=1)

log = -np.log(correct_confidences)
avg  = np.mean(log)

print(log)
print(avg)

[1.2039728  0.10536052 0.10536052]
0.4715646118805295


In [35]:
-np.log(0)

<ipython-input-35-bffa671ebd70>:1: RuntimeWarning: divide by zero encountered in log
  -np.log(0)


inf

In [36]:
np.e**(-np.inf)

0.0

In [37]:
np.e**(np.inf)

inf

In [38]:
-np.log(1e-7)

16.11809565095832

In [39]:
-np.log(1+1e-7)

-9.999999505838704e-08

In [40]:
-np.log(1-1e-7)

1.0000000494736474e-07

In [4]:
import numpy as np
softmax_output=np.array([[0.7, 0.1, 0.2],
                [0.1, 0.5, 0.4],
                [0.02, 0.9, 0.08]])

class_targets=np.array([[0, 1, 1],
                       [0, 1, 1],
                       [0, 1, 0]])

if len(class_targets.shape)==1:
  correct_confidences = [softmax_output[i][j] for i, j in enumerate(class_targets)]
  print(correct_confidences)

elif len(class_targets.shape)==2:
  correct_confidences = np.sum(softmax_output*class_targets, axis=1)

log = -np.log(correct_confidences)
avg  = np.mean(log)

print(log)
print(avg)

[1.2039728  0.10536052 0.10536052]
0.4715646118805295


In [2]:
!pip install nnfs

In [18]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_dense:
  def __init__(self, inputs, neurons):
    self.w = 0.01*np.random.randn(inputs, neurons)
    self.b = np.zeros((1, neurons))

  def forward(self, inputs):
    self.output = np.dot(inputs, self.w) + self.b


class Relu:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)

class Softmax:
  def forward(self, inputs):
    exp = np.exp(inputs - np.max(inputs, axis=1, keepdims =True))

    probabilities = exp/np.sum(exp, axis= 1, keepdims=True)
    self.output = probabilities

class Loss:
  def calculate(self, output, y):
      sample_loss = self.forward(output, y)
      data_loss = np.mean(sample_loss)
      return data_loss

class Catagorical_cross_entropy(Loss):
  def forward(self, y_pred, y_true):   # y_pred -> predicted value
                                         # y_true -> actiual value
      samples = len(y_pred)
      y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)


# pribalility of targey value
      if len(y_true.shape)==1:
         correct_confidences = y_pred_clipped[range(samples), y_true]

#     one-hor encoded lalbels
      elif len(y_true.shape)==2:
          correct_confidences = np.sum(y_pred_clipped * y_true, axis=1)
# losses
      negative_log_likelihoods = -np.log(correct_confidences)
      return negative_log_likelihoods



x, y =spiral_data(samples=100, classes=3)
dense1 = Layer_dense(2, 3)
activation1 = Relu()

dense2 = Layer_dense(3, 3)
activation2  = Softmax()

loss = Catagorical_cross_entropy()

dense1.forward(x)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:4])

loss = loss.calculate(activation2.output, y)

print(loss)



[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]]
1.0986104


In [19]:
predictions =np.argmax(activation2.output, axis =1)
if len(y.shape)==2:
  y =np.argmax(y, axis =1)
accuracy =np.mean(predictions==y)

print(accuracy)

0.34
