In [1]:
import numpy as np

In [4]:
softmax_output=[0.9, 0.5, 0.3]

softmax_output =np.array(softmax_output).reshape(-1,1)
print(softmax_output)

[[0.9]
 [0.5]
 [0.3]]


In [5]:
print(np.eye(softmax_output.shape[0]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
print(softmax_output * np.eye(softmax_output.shape[0]))

[[0.9 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.3]]


In [9]:
print(np.diagflat(softmax_output))

[[0.9 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.3]]


In [7]:
print(np.dot(softmax_output, softmax_output.T))

[[0.81 0.45 0.27]
 [0.45 0.25 0.15]
 [0.27 0.15 0.09]]


In [11]:
print(np.diagflat(softmax_output)-np.dot(softmax_output,softmax_output.T))

[[ 0.09 -0.45 -0.27]
 [-0.45  0.25 -0.15]
 [-0.27 -0.15  0.21]]


In [14]:
class Layer_dense:
  def __init__(self, inputs, n): #n = neurons
    self.w = 0.01* np.random.randn(inputs, n)
    self.b = np.zeros((1, n))

  def forward(self, inputs):
    self.outputs = np.dot(inputs, self.w) + self.b

class Relu:
  def forward(self, inputs):
    self.outputs = np.maximum(0, inputs)

class Layer_dense:
  def forward(self, inputs):
    self.inputs = inputs

class Layer_dense:
  def backward(self, dvalues):
    self.dw = np.dot(self.inputs.T, dvalues)
    self.db = np.sim(dvalues, axis=0, keepdims =True)
    self.dinputs = np.dot(dvalues, self.w.T)

class Relu:
  def forward(self, inputs):
    self.inputs = inputs
    self.outputs = np.maximum(0, inputs)
  def backward(self, dvalues):
    self.dinputs = dvalues.copy()
    self.dinputs[self.inputs<=0] = 0 # zero gradient inputs value were negative

class Loss:
  def calculate(self, output, y):
      sample_loss = self.forward(output, y)
      data_loss = np.mean(sample_loss)
      return data_loss
#-------------------------------------------------------------------------------
class Categorical_Cross_Entropy(Loss):
  def backward(self, dvalues, y_true):
    samples = len(dvalues)
    labels = len(dvalues[0])

    if len(y_true.shape)==1:
      y_true = np.eye(labels)[y_true]

    self.dinputs = -y_true / dvalues
    self.dinputs = self.dinputs / samples

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
class Softmax:
  def backward(self, dvalues):
    self.dinputs = np.empty_like(dvalues)

    for index, (single_output, single_dvalues) in \
                enumerate(zip(self.output, dvalues)):
            single_output = single_output.reshape(-1, 1)

            matrix = np.diagflat(single_output) - \
                              np.dot(single_output, single_output.T)


            self.dinputs[index] = np.dot(matrix,
                                         single_dvalues)
#-------------------------------------------------------------------------------